name: Deploy to Koyeb 

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push React app
        uses: docker/build-push-action@v4
        with:
          context: ./imdbmovies
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/react-app:latest

      - name: Build and push Node.js app
        uses: docker/build-push-action@v4
        with:
          context: ./node-backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nodejs:latest

      - name: Build and push Flask app
        uses: docker/build-push-action@v4
        with:
          context: ./ml-server
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask:latest

  deploy-to-koyeb:
    runs-on: ubuntu-latest
    needs: build-and-push
    env:
      MONGODB_URI:  ${{ secrets.MONGODB_URI }}
      KOYEB_APP: imdbsa
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Latest Koyeb CLI
        run: |
          curl -sL https://github.com/koyeb/koyeb-cli/releases/download/v5.5.0/koyeb-cli_5.5.0_linux_amd64.tar.gz | tar xz
          sudo mv koyeb /usr/local/bin

      - name: Create Koyeb Config File
        run: |
          echo "token: ${{ secrets.KOYEB_TOKEN }}" > /home/runner/.koyeb.yaml
        env:
          KOYEB_CONFIG: /home/runner/.koyeb.yaml

      - name: Create/Update Koyeb App
        run: |
          if ! koyeb app get $KOYEB_APP &> /dev/null; then
            koyeb app create $KOYEB_APP
          fi

      - name: Deploy React Frontend Service
        run: |
          koyeb service create react \
            --app $KOYEB_APP \
            --docker ${{ secrets.DOCKERHUB_USERNAME }}/react-app:latest \
            --port 3000:http \
            --route /:3000 \
            --env NODE_ENV=production \
            --env API_URL=https://api-$KOYEB_APP.koyeb.app \
            --instance-type nano || \
          koyeb service update react \
            --docker ${{ secrets.DOCKERHUB_USERNAME }}/react-app:latest

      - name: Deploy Node.js API Service
        run: |
          koyeb service create nodejs \
            --app $KOYEB_APP \
            --docker ${{ secrets.DOCKERHUB_USERNAME }}/nodejs:latest \
            --port 4000:http \
            --route /api:4000 \
            --env NODE_ENV=production \
            --env MONGODB_URI=$MONGODB_URI\
            --env FLASK_SERVICE_URL=http://flask:5000 \
            --instance-type nano || \
          koyeb service update nodejs \
            --docker ${{ secrets.DOCKERHUB_USERNAME }}/nodejs:latest

      - name: Deploy Flask ML Service
        run: |
          koyeb service create flask \
            --app $KOYEB_APP \
            --docker ${{ secrets.DOCKERHUB_USERNAME }}/flask:latest \
            --port 5000:http \
            --route /ml:5000 \
            --env FLASK_ENV=production \
            --instance-type nano || \
          koyeb service update flask \
            --docker ${{ secrets.DOCKERHUB_USERNAME }}/flask:latest
      - name: Get Public URL
        run: |
          echo "Your application is deployed at: https://$KOYEB_APP.koyeb.app"
